### ISSUE TITLE
Anne plugin relevant notification

### ISSUE THREAD

**Issue by Ahyaya** [GlowingTree880/L4D2_LittlePlugins#1]
Please notice that the Anne plugin has never published nor expressed the willingness to make published the source code.
It's clear that the Anne plugin is originally published at https://github.com/Caibiii/AnneServer without claiming its license type and using terms. As far as I know, the source code of AnneServer remain private because the authors are NOT prepared to full engage yet. 
Let alone if you have the right to release the unauthorized code, you are supposed to read and learn what exactly GPL is prior to using it.
I suggest that you should contact the author as soon as possible.

**Comment by GlowingTree880** [comment]
* Thanks for the report, I have changed the license of my project from LGPL-2.1 License to GPL-3.0 License and correct the author Information and url of that source code which related to AnneServer
* For Sourcemod plugins/extensions lincense, we can refer to this website：[ SourceMod License](https://www.sourcemod.net/license.php), we know clear that Sourcemod is licensed under the GPL, version 3 and it's derivative works (plugins/extensions included) must be under the GPL, version 3. So it means 
> if you distribute the binary file (.smx) version of any plugin, you are supposed to distribute the source along with it. If you do not do this, you violating the Sourcemod license. [Quoted from Sazpaimon](https://forums.alliedmods.net/showpost.php?p=1587691&postcount=10)
We can see that AnneServer's github is public and there are already many server owners using the plugin to create their own server. But AnneServer has so far not released the source code, this has violated the Sourcemod license.
* Then, about my code：those codes about AnneServer are NOT the real code of AnneServer's plugin, those codes are obtained in two steps：first decompiled the binary file (.smx) and then fixed the decompiled version. [About the decompilation behavior (Quoted from Silvers)](https://forums.alliedmods.net/showpost.php?p=2709004&postcount=394)
* [More informations about publishing plugins/source code and some questions about GPL License](https://forums.alliedmods.net/showpost.php?p=1648709&postcount=80)
* I am trying to contact the author now about his opinion on whether my project is infringing, If my project is infringing, I will delete those plugins which related to AnneServer as soon as possible.

**Comment by Ahyaya** [comment]
I have informed one of the authors of AnneServer as to the issue.

The author has NO objection against the decompilation, but he also claims that his team has no warranty for now and the future upon the plugin. He used github as a kind of netdisk to store some test versions, rather than to make published the plugin. 

Anyway, the team would not interfere in your repo, but please make sure that you remove any of "Anne"-like info within the *.smx files. They do not want to get bothered subsequently by something like bug reports.

About the spirit of GPL, please understand that there are reasons for why they could not reveal the code.
