### ISSUE TITLE
JockeyRideSpeed

### ISSUE THREAD

**Issue by Unfellowed** [GlowingTree880/L4D2_LittlePlugins#11]
In some cases, the Jockey bot will control the player and fly around the map causing the player to be killed instantly. I used Sir's Jockey Teleport Fix plugin to fix it but to no avail.
![Screenshot (269)](https://github.com/GlowingTree880/L4D2_LittlePlugins/assets/115072518/7fc7f99b-c021-4f40-b0cd-cd62d88df9ab)

**Comment by fantasylidong** [comment]
Just curious , Is jockey teleport pos is (0,0,0)？

**Comment by Unfellowed** [comment]
At that time, I didn't turn on cl_showpos to check, so I didn't know. The chance of this bug is about 30% and I don't know how to reproduce it. Here is my plugin list.
![Screenshot (278)](https://github.com/GlowingTree880/L4D2_LittlePlugins/assets/115072518/7a46a9c5-c20e-4eff-8ab0-6acc5bfc1e75)

**Comment by fantasylidong** [comment]
I think is not the plugin’s problem.
I open some PvE server which have the jockey teleport problem. Sir’s teleport fix plugin can’t help with it.
I unload many fixes plugins and fix it.
You can check out  [this url](https://github.com/fantasylidong/CompetitiveWithAnne/tree/master/cfg/cfgogl/annehappy)
See which plugins I unload. 
maybe this will help you find out problems.
