### ISSUE TITLE
关于simple_mode的提问

### ISSUE THREAD

**Issue by PIPDesign** [GlowingTree880/L4D2_LittlePlugins#17]
大佬，我在使用simple_mode时通过match指令更改模式短暂读条后会让所有人返回游戏主界面，控制台报如下错误。此时服务器并未崩溃，只是玩家都掉出去了。这个是哪里没配置好吗？而且不是所有地图都会这样，简单测试后，差不多官方图一半会掉出去，还有一部分可以正常切换模式
Wendy、 unpaused the game
Unknown command: sm_match
{B}[{W}SimpleModeVote{B}]: {G}{B}[{W}SimpleMode{B}]: {G}{B}[{W}SimpleMode{B}]: {G}{B}[{W}SimpleMode{B}]: {G}{B}[{W}SimpleMode{B}]: {G}Wendy、 unpaused the game
Wendy、 paused the game
Wendy、 unpaused the game
Wendy、 paused the game
Received wrong spawn count 11 when at 10
Commencing connection retry to public(0.0.0.0:24004)direct(121.60.91.149:24004)
failed processing
 Dumping messages for channel CLIENT(121.60.91.149:24004) 0x0A7AD5D0
Header bits 96, flags == 33
1 messages
0 -----------------------
net_SignonState: type( 7 ) group ( 13 ) size ( 136 bytes ), startbit 6 end bit 246
   net_SignonState: state 7, count 11
RAW(net_SignonState) start
net_SignonState  >>  .uf^......z.....'....... bc75665e 01000000 d0d57a0a 00000000 27000000 9f040000   
net_SignonState  >>  ...zX..@...............@ b9cac97a 589eda40 01000000 1e000000 0ea5ac95 e39fda40   
net_SignonState  >>  ........................ 01000000 1e000000 00000000 00000000 00000000 00000000   
net_SignonState  >>  ........ .Y............. 00000000 00000000 20005914 07000000 0b000000 00000000   
net_SignonState  >>  .....................*|. 00000000 00000000 00000000 00000000 00000000 802a7c06   
net_SignonState  >>   ............*|.         20000000 00000000 0d000000 802a7c06                     
RAW(net_SignonState) end
Raw
PKT  >>  .S...D..!.M............. b7530000 9e440000 21e94d01 cf0700c7 c1020000 00000000   
PKT  >>  ....@.....L[..Z...]X.@.  00000000 40030000 c0984c5b cc175ada 19da5d58 1e4080     
CAsyncWavDataCache:  563 .wavs total 0 bytes, 0.00 % of capacity
Duplicate sequence 3 in sheet file
survivors/survivor_NamVet.mdl/survivors/anim_namvet.mdl : missmatched parent bones on "ValveBiped.attachment_bandage_legL"
survivors/survivor_NamVet.mdl/xdreanims/bill_slot_008.mdl : missmatched parent bones on "ValveBiped.attachment_bandage_legL"
survivors/survivor_NamVet.mdl/survivors/anim_NamWet.mdl : missmatched parent bones on "ValveBiped.attachment_bandage_legL"
survivors/survivor_NamVet.mdl/survivors/gestures_NamVet.mdl : missmatched parent bones on "ValveBiped.attachment_bandage_legL"
Unable to access ChromeHTMLControllerUnable to access ChromeHTMLControllerBinkOpen( h:\game\steam\steamapps\common\left 4 dead 2\left4dead2\media\l4d2_background05.bik )

**Comment by PIPDesign** [comment]
经过测试，我发现使用tickrate破解后，加入100tick的配置参数就会出现这种情况，不带参数用默认30tick就可以正常切换模式

**Comment by Majestymo** [comment]
看不懂

**Comment by GlowingTree880** [comment]
请问是哪些官图会出现问题，插件是否有报错，玩家掉出服务器重新连接是否已经切换到需要切换的模式
个人分别使用原版 L4DToolz 和 TickrateEnabler 与 Lakwsh 的 L4DToolz 设置 100 tick 且 `fps_max 0` 的指令也是写在 `server.cfg` 的，测试了官图 c2，c5，c8，c10，c11，切换模式重启地图时并未有掉出服务器的问题，切换模式时 cfg 的读取顺序为 `confogl_plugins.cfg -> confogl.cfg -> server.cfg`，测试服务器发行版本为 CentOS Linux release 7.6.1810，SourceMod 平台版本 1.11.0.6840，MetaMod 版本 1.12.0-dev+1157

**Comment by PIPDesign** [comment]
那有可能是我其他插件还有冲突，最近工作忙，闲下来我再试验一下看看是什么原因导致的。感谢大佬解答




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GlowingTree880/L4D2_LittlePlugins"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月9日(星期四) 晚上6:46
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [GlowingTree880/L4D2_LittlePlugins] 关于simple_mode的提问 (Issue #17)





 
请问是哪些官图会出现问题，插件是否有报错，玩家掉出服务器重新连接是否已经切换到需要切换的模式
 个人分别使用原版 L4DToolz 和 TickrateEnabler 与 Lakwsh 的 L4DToolz 设置 100 tick 且 fps_max 0 的指令也是写在 server.cfg 的，测试了官图 c2，c5，c8，c10，c11，切换模式重启地图时并未有掉出服务器的问题，切换模式时 cfg 的读取顺序为 confogl_plugins.cfg -&gt; confogl.cfg -&gt; server.cfg，测试服务器发行版本为 CentOS Linux release 7.6.1810，SourceMod 平台版本 1.11.0.6840，MetaMod 版本 1.12.0-dev+1157

**Comment by txuk1x** [comment]
我也遇到这种情况，然后发现是在L4D_OnFirstSurvivorLeftSafeArea这里设置tick相关的一些cvar然后再一个模式直接换到另一个模式的加载过程中就有几率出现所有人退出到主菜单的情况。
