### ISSUE TITLE
Ai_Charger_2.0消息刷屏

### ISSUE THREAD

**Issue by AYSHSTUDIO** [GlowingTree880/L4D2_LittlePlugins#7]
MOD测试地图（tumtara）中当charge出现时聊天框会循环输出信息

爆破字符串结果：小 0.00，大 350.00
爆破字符串结果：小 0.00，大 350.00
爆破字符串结果：小 0.00，大 350.00
爆破字符串结果：小 0.00，大 350.00
爆破字符串结果：小 0.00，大 350.00
爆破字符串结果：小 0.00，大 350.00
爆破字符串结果：小 0.00，大 350.00

**Comment by GlowingTree880** [comment]
> MOD测试地图（tumtara）中当charge出现时聊天框会循环输出信息
> 
> 爆破字符串结果：小 0.00，大 350.00 爆破字符串结果：小 0.00，大 350.00 爆破字符串结果：小 0.00，大 350.00 爆破字符串结果：小 0.00，大 350.00 爆破字符串结果：小 0.00，大 350.00 爆破字符串结果：小 0.00，大 350.00 爆破字符串结果：小 0.00，大 350.00

你好(｡･ω･｡)，Ai Charger 2.0 相关插件及源代码已重新上传，并已在 TUMTaRA 和 TUMTaRA - infected 地图中测试刷新 Charger，已没有聊天框刷屏信息，请下载最新版本试试。这些聊天框信息是插件开发某次调试时打印获取 Cvar：ai_ChargerExtraTargetDistance 结果的信息，可能那时候只在源码中删除上传了源码而插件未更新上传

**Comment by AYSHSTUDIO** [comment]
> > MOD测试地图（tumtara）中当charge出现时聊天框会循环输出信息
> > 爆破字符串结果：小 0.00，大 350.00 爆破字符串结果：小 0.00，大 350.00 爆破字符串结果：小 0.00，大 350.00 爆破字符串结果：小 0.00，大 350.00 爆破字符串结果：小 0.00，大 350.00 爆破字符串结果：小 0.00，大 350.00 爆破字符串结果：小 0.00，大 350.00
> 
> 你好(｡･ω･｡)，Ai Charger 2.0 相关插件及源代码已重新上传，并已在 TUMTaRA 和 TUMTaRA - infected 地图中测试刷新 Charger，已没有聊天框刷屏信息，请下载最新版本试试。这些聊天框信息是插件开发某次调试时打印获取 Cvar：ai_ChargerExtraTargetDistance 结果的信息，可能那时候只在源码中删除上传了源码而插件未更新上传

感谢你的更新，问题已经修复
