### ISSUE TITLE
Question:ServerRpgWithDatabase数据库写入失败

### ISSUE THREAD

**Issue by yajiwa** [GlowingTree880/L4D2_LittlePlugins#8]
#### 描述问题：
数据库连接成功，自动建表也完成，游戏里可以使用!buy命令，写入数据库失败
载入和使用命令时有报错
#### 环境信息：
mysql：8.0.24 for Linux on x86_64 (Source distribution)

os：CentOS Linux release 7.9.2009 (Core)

##### 截图和日志:

载入和使用命令：

```
L 03/29/2023 - 05:15:09: [SM] Exception reported: invalid handle 0 (error: 4)
L 03/29/2023 - 05:15:09: [SM] Blaming: tree_server_rpg.smx
L 03/29/2023 - 05:15:09: [SM] Call stack trace:
L 03/29/2023 - 05:15:09: [SM]   [0] WriteFileLine
L 03/29/2023 - 05:15:09: [SM]   [1] Line 555, tree_server_rpg.sp::SavePlayerMessage
L 03/29/2023 - 05:15:09: [SM]   [2] Line 308, rpgdatabases\menus.sp::Say_CallBack

```
游戏内个人信息：

![image](https://user-images.githubusercontent.com/58063798/228369610-c87d8f70-6f40-4743-a437-84fee47f5e6b.png)

**Comment by GlowingTree880** [comment]
**你好，此问题是由于数据库日志模块未正确运作而造成的**

- 默认玩家聊天数据及日志记录位置位于 `sourcemod/ServerLog` 目录下，如下代码所示（可在 `tree_server_rpg` 第 98 至 99 行处更改日志保存位置）
`// 插件日志保存位置
#define LOG_PLAYERMESSAGE_PATH "/ServerLog/%s_ChatLog.log"
#define LOG_FILE_PATH "/ServerLog/TreeServer_Database.log"`
- 由于插件未自动创建此文件夹，如果 `sourcemod` 目录下没有 `ServerLog` 文件夹则会导致插件无法创建日志文件报错（类似于 Linux 系统 `mkdir` 命令，不使用级联创建会导致创建多级文件失败）
- 接着玩家进入服务器时触发 `OnClientPostAdminCheck()` 函数，由于先进行日志记录发生错误，函数停止执行，无法执行 `InsertPlayerInfo()` 函数将玩家信息写入数据库中从而导致后续对玩家信息的更新操作失效

**解决方法**
1. 在 `sourcemod` 目录下手动创建 `ServerLog` 文件夹或更改日志保存位置为现有文件夹
2. 删除数据库中已有的表，重新进入游戏，待建表完成后查看玩家信息是否可以正确插入，退出时玩家信息是否可以正确更新

这个问题将会在不久后更新修复，更改为使用插件自动创建 ServerLog 文件夹 (｡･ω･｡)
