### ISSUE TITLE
infected_control.sp里面是否有个函数没有更新

### ISSUE THREAD

**Issue by Majestymo** [GlowingTree880/L4D2_LittlePlugins#9]
你好树树子，你是否忘了更新在infected_control.sp第896行GetRandomMobileSurvivor这个函数，新版的treeutil里面改成了GetRandomSurvivorAndValid这个函数https://github.com/GlowingTree880/L4D2_LittlePlugins/blob/main/Infected_Control_Rework/infected_control.sp

**Comment by GlowingTree880** [comment]
是的，更新完 treeutil 后没有再更新过 infected  crontol rework 了，感谢你的提出(｡･ω･｡)

- 请将 896 行更改为 `if (!IsValidSurvivor(target)) { target = GetRandomSurvivorAndValid(-1, false); }`，同时 900 行更改为 `target = GetRandomSurvivorAndValid(target, false);` 再次编译即可
ps：其实 infected control rework 写的很差强人意，优先找高位只有在特定位置才能体现出作用，否则会拖慢找位速度，不如直接使用射线，而且有时刷着刷着就不刷了，如果效果不好的话还是建议使用老版本的或者是电信服药役的 infected control 😢
